force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalProductCount__c.field-meta.xml
<CustomField>
    <fullName>TotalProductCount__c</fullName>
    <label>Total Product Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>Order Id</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderTriggerHandler.cls
public with sharing class OrderTriggerHandler {
    public static void onBeforeUpdate(Map<Id, Order__c> ordersMap) {
        updateTotals(ordersMap);
    }
    static void updateTotals(Map<Id, Order__c> ordersMap) {
        // get related orderItems
        Set<Id> ids = ordersMap.keySet();
        List<OrderItem__c> orderItems = new List<OrderItem__c>(
            [
                SELECT Id, Price__c, Quantity__c, OrderId__c
                FROM OrderItem__c
                WHERE OrderId__c IN :ids
            ]
        );

        // populate order-orderItems map
        Map<Id, List<OrderItem__c>> result = new Map<Id, List<OrderItem__c>>();
        for (OrderItem__c orderItem : orderItems) {
            if (!result.ContainsKey(orderItem.OrderId__c)) {
                result.put(orderItem.OrderId__c, new List<OrderItem__c>());
            }
            result.get(orderItem.OrderId__c).add(orderItem);
        }

        // calculate totals
        for (Id id : result.keySet()) {
            ordersMap.get(id).TotalPrice__c = 0;
            ordersMap.get(id).TotalProductCount__c = 0;
            for (OrderItem__c orderItem : result.get(id)) {
                ordersMap.get(id).TotalPrice__c +=
                    orderItem.Price__c * orderItem.Quantity__c;
                ordersMap.get(id).TotalProductCount__c += orderItem.Quantity__c;
            }
        }
    }
}