force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalProductCount__c.field-meta.xml
<CustomField>
    <fullName>TotalProductCount__c</fullName>
    <label>Total Product Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>Order Id</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <label>Product Id</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Families</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderTriggerTest.cls
@isTest
private class OrderTriggerTest {
    private class RestMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{"data":[{"id":1250, "imageurl":"testurl.com"}]}';

            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    @isTest
    static void TestOnBeforeUpdate() {
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Product__c testProduct = new Product__c(
            Name = 'TestProduct',
            Description__c = 'TestProduct description',
            Type__c = 'Type 1',
            Family__c = 'Family 1',
            Price__c = 100
        );
        insert testProduct;

        Order__c order = new Order__c(Name = 'testOrder');
        insert order;

        OrderItem__c orderItem = new OrderItem__c(
            Name = 'test item',
            Quantity__c = 10,
            Price__c = 5,
            OrderId__c = order.id,
            ProductId__c = testProduct.Id
        );
        Test.startTest();
        insert orderItem;
        Test.stopTest();
        order = [
            SELECT Id, TotalPrice__c, TotalProductCount__c
            FROM Order__c
            WHERE Id = :order.Id
        ][0];
        system.assertEquals(
            orderItem.Quantity__c * orderItem.Price__c,
            order.TotalPrice__c
        );
        system.assertEquals(orderItem.Quantity__c, order.TotalProductCount__c);
    }
}